# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        JTIR\UserBundle\Entity\Enseignant: sha512 #Hashage du mot de passe avec sha512

    role_hierarchy:
        ROLE_ELEVE: ROLE_ELEVE
        ROLE_ENSEIGNANT: ROLE_ENSEIGNANT
        ROLE_ADMIN: [ROLE_USER, ROLE_ELEVE, ROLE_ENSEIGNANT, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # Fournisseur d'utilisateur (Les firewalls s'adressent aux providers pour récupérer les utilisateurs et les identifier)
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    # Les différents pare-feu
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider: fos_userbundle # Le "fournisseur" d'utilisateur
            form_login:
                login_path: fos_user_security_login # Route vers le formulaire de connexion
                check_path: fos_user_security_check # Route pour la soumission du formulaire
            logout:
                path: fos_user_security_logout
                target: / # Redirection après la déconnexion
            remember_me:
                secret: %secret%

    # Le contrôle d'accès va s'occuper de déterminer si le visiteur a les bons droits (rôles) pour accéder à la ressource demandée.
    access_control:
        #- { path: ^/eleve, roles: ROLE_ELEVE }
        - { path: ^/enseignant, roles: ROLE_ENSEIGNANT }
