#####################################
# ROUTES POUR LES PAGES ENSEIGNANTS #
#####################################
jtir_enseignants_inscrire_classe:
    path:     /enseignants/creer-classe
    defaults: { _controller: JTIRUserBundle:Enseignants:classe }

jtir_enseignants_bibliotheque:
    path:     /enseignants/bibliotheque
    defaults: { _controller: JTIRUserBundle:Enseignants:bibliotheque }

jtir_enseignants_partenariat:
    path:     /enseignants/partenariat
    defaults: { _controller: JTIRUserBundle:Enseignants:partenariat }

jtir_enseignants_dashboard:
    path:     /enseignants/dashboard
    defaults: { _controller: JTIRUserBundle:Enseignants:dashboard }

jtir_enseignants_tuto:
    path:     /enseignants/tutoriels
    defaults: { _controller: JTIRUserBundle:Enseignants:tutoriel }

#####################################
# ROUTES POUR LES PAGES ELEVES      #
#####################################
jtir_eleves_creation_conte:
    path:     /eleves/creer-conte
    defaults: { _controller: JTIRUserBundle:Eleves:creer }

jtir_eleves_modifier_conte:
    path:     /eleves/modifier-conte
    defaults: { _controller: JTIRUserBundle:Eleves:modifier }

jtir_eleves_bibliotheque:
    path:     /eleves/bibliotheque
    defaults: { _controller: JTIRUserBundle:Eleves:bibliotheque }
