# Overwrite des routes du bundle FOSUser
fos_user_security_login:
    path: /connexion
    defaults: { _controller: FOSUserBundle:Security:login }
    methods: [GET, POST]

fos_user_security_check:
    path: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    methods: [GET, POST]
