services:
    jtir_userbundle.detecterroles: # Le nom du service
        class: JTIR\UserBundle\Utils\DetecterRoles # La classe du service
        arguments: ['@security.authorization_checker', '@router']
        # Les deux services de Symfony que notre service va avoir besoin
